#!/usr/bin/env python3
"""
img2pixel.py — Convert an image to PixelBuffer-compatible JS code.

Usage:
    python3 tools/img2pixel.py <input_image> [options]

Options:
    -W, --width N       Target width in pixels  (default: 320)
    -H, --height N      Target height in pixels (default: 180)
    -n, --colors N      Palette size when auto-extracting (default: 32)
    -p, --palette FILE  Use palette from JSON file (list of hex strings)
    -o, --output FILE   Write JS to FILE (default: stdout)
    --preview FILE      Write quantized preview PNG (default: <input>_preview.png)
    --no-preview        Skip preview output
    --name NAME         JS variable name prefix (default: SCENE)
    --dither            Apply Floyd-Steinberg dithering before quantization
"""

import argparse
import json
import sys
from pathlib import Path
from PIL import Image


def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def rgb_to_hex(r, g, b):
    return f'#{r:02x}{g:02x}{b:02x}'


def color_distance(c1, c2):
    # Weighted Euclidean — perceptually balanced (green more sensitive)
    dr, dg, db = c1[0]-c2[0], c1[1]-c2[1], c1[2]-c2[2]
    return 2*dr*dr + 4*dg*dg + 3*db*db


def nearest_index(rgb, palette_rgb):
    best_i, best_d = 0, float('inf')
    for i, p in enumerate(palette_rgb):
        d = color_distance(rgb, p)
        if d < best_d:
            best_d, best_i = d, i
    return best_i


def extract_palette(img, n_colors):
    """Extract representative colors via PIL median-cut quantization."""
    rgb = img.convert('RGB')
    q = rgb.quantize(colors=n_colors, method=Image.Quantize.MEDIANCUT, dither=0)
    raw = q.getpalette()[:n_colors * 3]
    return [(raw[i], raw[i+1], raw[i+2]) for i in range(0, len(raw), 3)]


def dither_to_palette(img, palette_rgb, width, height):
    """Floyd-Steinberg dither the image to the given palette."""
    # Build a fake palette image PIL can use for dithering
    pal_img = Image.new('P', (1, 1))
    flat = []
    for r, g, b in palette_rgb:
        flat += [r, g, b]
    flat += [0] * (768 - len(flat))  # pad to 256 colors
    pal_img.putpalette(flat)

    resized = img.convert('RGB').resize((width, height), Image.LANCZOS)
    quantized = resized.quantize(palette=pal_img, dither=Image.Dither.FLOYDSTEINBERG)
    return list(quantized.getdata())


def quantize_to_palette(img, palette_rgb, width, height):
    """Map each pixel to nearest palette index (no dithering)."""
    resized = img.convert('RGB').resize((width, height), Image.LANCZOS)
    raw = resized.tobytes()
    pixels = [(raw[i], raw[i+1], raw[i+2]) for i in range(0, len(raw), 3)]
    return [nearest_index(p, palette_rgb) for p in pixels]


def make_preview(indices, palette_rgb, width, height, scale=4):
    """Upscale the quantized result for easy visual inspection."""
    out = Image.new('RGB', (width * scale, height * scale))
    rows = []
    for y in range(height):
        row = [palette_rgb[indices[y * width + x]] for x in range(width)]
        rows.append(row)
    data = []
    for row in rows:
        for _ in range(scale):
            for color in row:
                data.extend([color] * scale)
    out.putdata(data)
    return out


def generate_js(indices, palette_hex, width, height, name):
    lines = [
        f'// Generated by img2pixel.py — {width}×{height}, {len(palette_hex)} colors',
        f'const {name}_PALETTE = [',
    ]
    for i, h in enumerate(palette_hex):
        lines.append(f"  '{h}', // {i}")
    lines += ['];', '']

    lines.append(f'const {name}_PIXELS = new Uint8Array([')
    for y in range(height):
        row = indices[y * width:(y + 1) * width]
        # 32 values per line for readability
        chunks = [row[i:i+32] for i in range(0, width, 32)]
        line = '  ' + ',  '.join(', '.join(map(str, c)) for c in chunks) + ','
        lines.append(line)
    lines += [']);', '']

    lines += [
        '// Usage:',
        f'// const pb = new PixelBuffer({width}, {height}, {name}_PALETTE);',
        f'// pb.buf.set({name}_PIXELS);',
        "// pb.toSVG(document.getElementById('svg'));",
    ]
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description='Convert image to PixelBuffer JS code')
    parser.add_argument('input', help='Input image path')
    parser.add_argument('-W', '--width',   type=int, default=320)
    parser.add_argument('-H', '--height',  type=int, default=180)
    parser.add_argument('-n', '--colors',  type=int, default=32,
                        help='Palette size for auto-extraction (default: 32)')
    parser.add_argument('-p', '--palette', help='JSON file with hex color list')
    parser.add_argument('-o', '--output',  help='Output JS file (default: stdout)')
    parser.add_argument('--preview',       help='Preview PNG path')
    parser.add_argument('--no-preview',    action='store_true')
    parser.add_argument('--name',          default='SCENE',
                        help='JS variable prefix (default: SCENE)')
    parser.add_argument('--dither',        action='store_true',
                        help='Apply Floyd-Steinberg dithering')
    args = parser.parse_args()

    img_path = Path(args.input)
    if not img_path.exists():
        print(f'Error: {img_path} not found', file=sys.stderr)
        sys.exit(1)

    img = Image.open(img_path)

    # Palette: load from file or auto-extract
    if args.palette:
        with open(args.palette) as f:
            palette_hex = json.load(f)
        palette_rgb = [hex_to_rgb(h) for h in palette_hex]
        print(f'Palette: {len(palette_hex)} colors loaded from {args.palette}', file=sys.stderr)
    else:
        palette_rgb = extract_palette(img, args.colors)
        palette_hex = [rgb_to_hex(*c) for c in palette_rgb]
        print(f'Palette: {len(palette_hex)} colors auto-extracted', file=sys.stderr)

    # Quantize
    if args.dither:
        indices = dither_to_palette(img, palette_rgb, args.width, args.height)
        print(f'Dithering: Floyd-Steinberg', file=sys.stderr)
    else:
        indices = quantize_to_palette(img, palette_rgb, args.width, args.height)

    print(f'Output: {args.width}×{args.height} = {len(indices)} pixels', file=sys.stderr)

    # JS output
    js = generate_js(indices, palette_hex, args.width, args.height, args.name)
    if args.output:
        Path(args.output).write_text(js)
        print(f'JS written to {args.output}', file=sys.stderr)
    else:
        print(js)

    # Preview
    if not args.no_preview:
        preview_path = args.preview or (img_path.stem + '_preview.png')
        make_preview(indices, palette_rgb, args.width, args.height).save(preview_path)
        print(f'Preview saved to {preview_path}', file=sys.stderr)


if __name__ == '__main__':
    main()
